library('quantmod')

#Question1
#(a)
getSymbols("CAT", from="2007-01-03", to="2018-12-31",
           src="yahoo", auto.assign=TRUE)
getSymbols("PG", from="2007-01-03", to="2018-12-31",
           src="yahoo", auto.assign=TRUE)
getSymbols("^DJI", from="2007-01-03", to="2018-12-31",
           src="yahoo", auto.assign=TRUE)

chartSeries(CAT, theme="white")
chartSeries(PG, theme="white")
chartSeries(DJI, theme="white")

#(b)
library(fBasics)

Pc <- CAT$CAT.Adjusted
Rc <- diff(Pc)/lag(Pc)
rc <- diff(log(Pc))
head(Rc)
basicStats(Rc)

Pp <- PG$PG.Adjusted
Rp <- diff(Pp)/lag(Pp)
rp <- diff(log(Pp))
head(Rp)
basicStats(Rp)

Pd <- DJI$DJI.Adjusted
Rd <- diff(Pd)/lag(Pd)
rd <- diff(log(Pd))
head(Rd)
basicStats(Rd)

#(c)
qqnorm(as.vector(rc), datax = TRUE, main = "normal plot for Caterpillar stock",
       xlab = "normal quantile", 
       ylab = "sample quantile") 
qqline(as.vector(rc), datax=TRUE, col = 2)
#Log return for Caterpillar stock is not normally distributed

qqnorm(as.vector(rp), datax = TRUE, main = "normal plot for Procter & Gamble stock",
       xlab = "normal quantile", 
       ylab = "sample quantile") 
qqline(as.vector(rp), datax=TRUE, col = 2)
#Log return for Procter & Gamble stock is not normally distributed

qqnorm(as.vector(rd), datax = TRUE, main = "normal plot for Dow Jones Industrial Average",
       xlab = "normal quantile", 
       ylab = "sample quantile") 
qqline(as.vector(rd), datax=TRUE, col = 2)
#Log return for Dow Jones Industrial Average is not normally distributed

#(d)
par(mfrow=c(1,3))
n = dim(rc)[1]
grid = (1:n)/(n+1)
for (tdf in c(2, 3, 4)){
    qqplot(as.vector(rc), qt(grid,df=tdf),
           main= paste("t-probability plot, df =", tdf),
           xlab="Sample",ylab="t-quantiles")
    qntl = quantile(as.vector(rc), probs = c(0.25,0.75), na.rm=TRUE, names=FALSE)
    abline( lm( qt(c(.25,.75),df = tdf) ~ qntl ), col = 2)
}
#The good fit t distribution would be when df around 3.

par(mfrow=c(1,3))
n = dim(rp)[1]
grid = (1:n)/(n+1)
for (tdf in c(2, 3, 4)){
    qqplot(as.vector(rp), qt(grid,df=tdf),
           main= paste("t-probability plot, df =", tdf),
           xlab="Sample",ylab="t-quantiles")
    qntl = quantile(as.vector(rp), probs = c(0.25,0.75), na.rm=TRUE, names=FALSE)
    abline( lm( qt(c(.25,.75),df = tdf) ~ qntl ), col = 2)
}
#The good fit t distribution would be when df around 3.

par(mfrow=c(1,3))
n = dim(rd)[1]
grid = (1:n)/(n+1)
for (tdf in c(2, 2.5, 3)){
    qqplot(as.vector(rd), qt(grid,df=tdf),
           main= paste("t-probability plot, df =", tdf),
           xlab="Sample",ylab="t-quantiles")
    qntl = quantile(as.vector(rd), probs = c(0.25,0.75), na.rm=TRUE, names=FALSE)
    abline( lm( qt(c(.25,.75),df = tdf) ~ qntl ), col = 2)
}
#The good fit t distribution would be when df around 2.5.

#Question2
#(a)
# YY is not normally distributed, it indicates a light tail comparing to the normal distribution.
# ZZ is not normally distributed, it indicates a right skewness comparing to the normal distribution.
# TT is not normally distributed, it indicates a left skewness comparing to the normal distribution.
# EE is not normally distributed, it indicates a right skewness comparing to the normal distribution.

#(b)
rnormx <- rnorm(100)
qqnorm(as.vector(rnormx), datax = TRUE, main = "normal plot for rnorm",
       xlab = "normal quantile", 
       ylab = "sample quantile") 
qqline(as.vector(rnormx), datax=TRUE, col = 2)
# rnorm is not normally distributed, it indicates a silghtly light tail.

#(c)
rexpy <- rexp(100, 1)
qqnorm(as.vector(rexpy), datax = TRUE, main = "normal plot for rexp",
       xlab = "normal quantile", 
       ylab = "sample quantile") 
qqline(as.vector(rexpy), datax=TRUE, col = 2)
# rexp is not normally distributed, it indicates a right skewness.

#(d)
qqnorm(as.vector(rnormx), datax = TRUE, main = "normal plot for rnorm",
       xlab = "normal quantile", 
       ylab = "sample quantile") 
qqline(as.vector(rnormx), datax=TRUE, col = 2)
qqnorm(as.vector(rexpy), datax = TRUE, main = "normal plot for rexp",
       xlab = "normal quantile", 
       ylab = "sample quantile") 
qqline(as.vector(rexpy), datax=TRUE, col = 2)
#The sample generated by rnorm are close to normal distribution in the middle, but gets some variance
#on the side. It can be either light tail or heavy tail.
#While the sample generated by rexp are not normally distributed, and always indicated a right skewness. 